# Generated by Django 2.0 on 2018-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180112_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
