# Generated by Django 2.0 on 2018-01-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180112_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved',
            field=models.IntegerField(default=1),
        ),
    ]
