# Generated by Django 2.0 on 2018-01-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180112_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-solved', 'timetaken']},
        ),
    ]
