# Generated by Django 2.0 on 2018-01-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180112_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='image',
            field=models.BooleanField(default=False),
        ),
    ]
