# Generated by Django 2.0 on 2018-01-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180117_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
